### ISSUE TITLE
OAuth-1.2.3 install on PHP 7 fails with: /tmp/pear/temp/oauth/php_oauth.h:35:40: fatal error: ext/standard/php_smart_str.h: No such file or directory

### ISSUE THREAD

**Issue by therobyouknow** [Sean-Der/pecl-web_services-oauth#14]
Could you advise, please? (I need to use OAuth 1.0a) Thank you.

```
$ sudo pecl install oauth-1.2.3
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading oauth-1.2.3.tgz ...
Starting to download oauth-1.2.3.tgz (45,531 bytes)
.............done: 45,531 bytes
6 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
building in /tmp/pear/temp/pear-build-rootoSu4IJ/oauth-1.2.3
running: /tmp/pear/temp/oauth/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20151012
checking for PHP installed headers prefix... /usr/include/php/20151012
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for oauth support... yes, shared
checking for cURL in default path... cURL not found
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /tmp/pear/temp/pear-build-rootoSu4IJ/oauth-1.2.3/libtool --mode=compile cc  -I. -I/tmp/pear/temp/oauth -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootoSu4IJ/oauth-1.2.3/include -I/tmp/pear/temp/pear-build-rootoSu4IJ/oauth-1.2.3/main -I/tmp/pear/temp/oauth -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall -g   -c /tmp/pear/temp/oauth/oauth.c -o oauth.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/oauth -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootoSu4IJ/oauth-1.2.3/include -I/tmp/pear/temp/pear-build-rootoSu4IJ/oauth-1.2.3/main -I/tmp/pear/temp/oauth -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -Wall -g -c /tmp/pear/temp/oauth/oauth.c  -fPIC -DPIC -o .libs/oauth.o
In file included from /tmp/pear/temp/oauth/oauth.c:14:0:
/tmp/pear/temp/oauth/php_oauth.h:35:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include "ext/standard/php_smart_str.h"
                                        ^
compilation terminated.
make: *** [oauth.lo] Error 1
ERROR: `make' failed

```

**Comment by therobyouknow** [comment]
Issue appears to be something to do with my PHP 7 setup (puphpet.com vagrant provisioned VM - Ubuntu 14.04 LTS) But Appears to work on 5.5 (Ubuntu 12.04 LTS 64bit):

```
[09:31 AM]-[vagrant@u1204php55]-[~] 
$ sudo pecl install oauth-1.2.3
downloading oauth-1.2.3.tgz ...
Starting to download oauth-1.2.3.tgz (45,531 bytes)
.............done: 45,531 bytes
6 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
building in /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3
running: /tmp/pear/temp/oauth/configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib
checking for PHP extension directory... /usr/lib/php5/20121212
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for oauth support... yes, shared
checking for cURL in default path... cURL not found
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/libtool --mode=compile cc  -I. -I/tmp/pear/temp/oauth -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/include -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/main -I/tmp/pear/temp/oauth -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall -g   -c /tmp/pear/temp/oauth/oauth.c -o oauth.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/oauth -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/include -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/main -I/tmp/pear/temp/oauth -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -Wall -g -c /tmp/pear/temp/oauth/oauth.c  -fPIC -DPIC -o .libs/oauth.o
/tmp/pear/temp/oauth/oauth.c: In function 'soo_sign_hmac':
/tmp/pear/temp/oauth/oauth.c:260:6: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
/tmp/pear/temp/oauth/oauth.c: In function 'soo_sign_rsa':
/tmp/pear/temp/oauth/oauth.c:305:6: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
/tmp/pear/temp/oauth/oauth.c: In function 'oauth_compare_key':
/tmp/pear/temp/oauth/oauth.c:507:19: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
/tmp/pear/temp/oauth/oauth.c:516:20: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
/bin/bash /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/libtool --mode=compile cc  -I. -I/tmp/pear/temp/oauth -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/include -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/main -I/tmp/pear/temp/oauth -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall -g   -c /tmp/pear/temp/oauth/provider.c -o provider.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/oauth -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/include -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/main -I/tmp/pear/temp/oauth -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -Wall -g -c /tmp/pear/temp/oauth/provider.c  -fPIC -DPIC -o .libs/provider.o
/tmp/pear/temp/oauth/provider.c: In function 'zim_oauthprovider_isRequestTokenEndpoint':
/tmp/pear/temp/oauth/provider.c:644:22: warning: variable 'sop' set but not used [-Wunused-but-set-variable]
/bin/bash /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/libtool --mode=link cc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/include -I/tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/main -I/tmp/pear/temp/oauth -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall -g   -o oauth.la -export-dynamic -avoid-version -prefer-pic -module -rpath /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/modules  oauth.lo provider.lo
libtool: link: cc -shared  -fPIC -DPIC  .libs/oauth.o .libs/provider.o    -O2   -Wl,-soname -Wl,oauth.so -o .libs/oauth.so
libtool: link: ( cd ".libs" && rm -f "oauth.la" && ln -s "../oauth.la" "oauth.la" )
/bin/bash /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/libtool --mode=install cp ./oauth.la /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/modules
libtool: install: cp ./.libs/oauth.so /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/modules/oauth.so
libtool: install: cp ./.libs/oauth.lai /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/modules/oauth.la
libtool: finish: PATH="/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/pear/temp/pear-build-rootRQtz9r/oauth-1.2.3/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

running: make INSTALL_ROOT="/tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3" install
Installing shared extensions:     /tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3/usr/lib/php5/20121212/
running: find "/tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3" | xargs ls -dils
1310856   4 drwxr-xr-x 3 root root   4096 Aug 18 09:32 /tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3
1310880   4 drwxr-xr-x 3 root root   4096 Aug 18 09:32 /tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3/usr
1310881   4 drwxr-xr-x 3 root root   4096 Aug 18 09:32 /tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3/usr/lib
1310882   4 drwxr-xr-x 3 root root   4096 Aug 18 09:32 /tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3/usr/lib/php5
1310883   4 drwxr-xr-x 2 root root   4096 Aug 18 09:32 /tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3/usr/lib/php5/20121212
1310879 308 -rwxr-xr-x 1 root root 314290 Aug 18 09:32 /tmp/pear/temp/pear-build-rootRQtz9r/install-oauth-1.2.3/usr/lib/php5/20121212/oauth.so

Build process completed successfully
Installing '/usr/lib/php5/20121212/oauth.so'
install ok: channel://pecl.php.net/oauth-1.2.3
configuration option "php_ini" is not set to php.ini location
You should add "extension=oauth.so" to php.ini

[09:32 AM]-[vagrant@u1204php55]-[~]
```

**Comment by VegasJames** [comment]
Actually, I'm having this problem too, so I don't think it's something specific to your setup. I'm on CentOS 7.

**Comment by BBCInnovins** [comment]
Has anyone found solution to this problem. Facing the same issue

**Comment by raza1337** [comment]
Facing the same issue any solution?
